openapi: 3.0.4
info:
  title: CoAP Proxy API (for CoAP clients)
  version: 1.0.0
  description: |
    **This API describes a CoAP-to-HTTP proxy.**

    - The endpoints are designed to be accessed by CoAP clients (IoT sensors, devices, etc.), not directly by HTTP clients.
    - This documentation is for reference and integration purposes.
    - The proxy receives CoAP requests and forwards them to an HTTP backend.
