services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  aiolos-backend:
    image: ghcr.io/resonect-technology/aiolos-backend:latest
    container_name: aiolos-backend
    restart: unless-stopped
    ports:
      - "3030:3000"
    networks:
      - aiolos-network

  aiolos-frontend:
    image: ghcr.io/resonect-technology/aiolos-frontend:latest
    container_name: aiolos-frontend
    restart: unless-stopped
    ports:
      - "3040:3000"
    networks:
      - aiolos-network
    environment:
      - NEXT_PUBLIC_API_URL=http://aiolos-backend:3000

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - aiolos-network

networks:
  aiolos-network:
    driver: bridge
