services:
  backend:
    image: 590183887485.dkr.ecr.eu-central-1.amazonaws.com/aiolos-backend:latest
    container_name: aiolos-backend
    platform: linux/arm64
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - sqlite_data:/app/tmp
    expose:
      - 8080
    # Add environment variables to help with better-sqlite3 bindings
    environment:
      - npm_config_platform=linux
      - npm_config_arch=arm64
      - npm_config_target_arch=arm64
      - npm_config_target_platform=linux
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/healthcheck" , "||", "exit", "1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s # Increased to allow more time for startup
    command: >
      sh -c "
        node ace migration:run --force &&
        node ace db:seed &&
        node bin/server.js
      "

  frontend:
    image: 590183887485.dkr.ecr.eu-central-1.amazonaws.com/aiolos-frontend:latest
    container_name: aiolos-frontend
    platform: linux/arm64
    volumes:
      - frontend-dist:/dist
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    container_name: aiolos-caddy
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - frontend-dist:/srv
      - caddy_data:/data
    depends_on:
      - backend
    environment:
      - AIOLOS_BACKEND_HOST=backend:8080

volumes:
  frontend-dist:
  caddy_data:
  sqlite_data:
