services:
  backend:
    image: 590183887485.dkr.ecr.eu-central-1.amazonaws.com/aiolos-backend:latest
    platform: linux/arm64
    env_file:
      - .env
    restart: unless-stopped
    expose:
      - 8080

  frontend:
    image: 590183887485.dkr.ecr.eu-central-1.amazonaws.com/aiolos-frontend:latest
    platform: linux/arm64
    volumes:
      - frontend-dist:/dist
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - frontend-dist:/srv
      - caddy_data:/data
    depends_on:
      - backend
    environment:
      - AIOLOS_BACKEND_HOST=backend:8080

volumes:
  frontend-dist:
  caddy_data:
