services:
  backend:
    image: 590183887485.dkr.ecr.eu-central-1.amazonaws.com/aiolos-backend:latest
    container_name: aiolos-backend
    platform: linux/arm64
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      # Bind mount for database - easier backups and management
      - ./data:/app/tmp
    expose:
      - 8080
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/healthcheck",
        ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s

  frontend:
    image: 590183887485.dkr.ecr.eu-central-1.amazonaws.com/aiolos-frontend:latest
    container_name: aiolos-frontend
    platform: linux/arm64
    volumes:
      - frontend-dist:/dist
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    container_name: aiolos-caddy
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - frontend-dist:/srv
      - caddy_data:/data
    depends_on:
      - backend
    environment:
      - AIOLOS_BACKEND_HOST=backend:8080

volumes:
  frontend-dist:
  caddy_data:
  # Removed sqlite_data volume - now using bind mount
