name: Build and Deploy Aiolos

on:
  workflow_dispatch:

jobs:
  build-and-push-backend:
    name: Build and Push Backend
    runs-on: [resonect-server]
    env:
      ENVIRONMENT: production
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.RESONECT_AWS_PROD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.RESONECT_AWS_PROD_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.RESONECT_AWS_PROD_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/adonis-api/Dockerfile
          push: true
          platforms: linux/arm64
          tags: |
            ${{ secrets.RESONECT_AWS_PROD_ID }}.dkr.ecr.eu-central-1.amazonaws.com/aiolos-backend:latest
            ${{ secrets.RESONECT_AWS_PROD_ID }}.dkr.ecr.eu-central-1.amazonaws.com/aiolos-backend:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.RESONECT_AWS_PROD_ID }}.dkr.ecr.eu-central-1.amazonaws.com/aiolos-backend:buildcache
          cache-to: type=registry,ref=${{ secrets.RESONECT_AWS_PROD_ID }}.dkr.ecr.eu-central-1.amazonaws.com/aiolos-backend:buildcache,mode=max

  build-and-push-frontend:
    name: Build and Push Frontend
    runs-on: [resonect-server]
    env:
      ENVIRONMENT: production
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.RESONECT_AWS_PROD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.RESONECT_AWS_PROD_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.RESONECT_AWS_PROD_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/react-frontend/Dockerfile
          push: true
          platforms: linux/arm64
          tags: |
            ${{ secrets.RESONECT_AWS_PROD_ID }}.dkr.ecr.eu-central-1.amazonaws.com/aiolos-frontend:latest
            ${{ secrets.RESONECT_AWS_PROD_ID }}.dkr.ecr.eu-central-1.amazonaws.com/aiolos-frontend:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.RESONECT_AWS_PROD_ID }}.dkr.ecr.eu-central-1.amazonaws.com/aiolos-frontend:buildcache
          cache-to: type=registry,ref=${{ secrets.RESONECT_AWS_PROD_ID }}.dkr.ecr.eu-central-1.amazonaws.com/aiolos-frontend:buildcache,mode=max

  deploy:
    name: Deploy to Production
    needs: [build-and-push-backend, build-and-push-frontend]
    runs-on: [resonect-server]
    env:
      ENVIRONMENT: production
      AWS_ACCESS_KEY_ID: ${{ secrets.RESONECT_AWS_PROD_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.RESONECT_AWS_PROD_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.RESONECT_AWS_PROD_REGION }}
    steps:
      - uses: actions/checkout@v4

      - name: Prepare EC2 instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AIOLOS_PROD_EC2_HOST }}
          username: ${{ secrets.AIOLOS_PROD_EC2_USER }}
          key: ${{ secrets.RESONECT_AWS_PROD_SSH_KEY }}
          script: |
            # Create directory if it doesn't exist
            mkdir -p ~/aiolos

      - name: Copy configuration files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AIOLOS_PROD_EC2_HOST }}
          username: ${{ secrets.AIOLOS_PROD_EC2_USER }}
          key: ${{ secrets.RESONECT_AWS_PROD_SSH_KEY }}
          source: ./infra/docker-compose.prod.yml,./infra/Caddyfile,./apps/adonis-api/.env
          target: ~/aiolos
          strip_components: 2

      - name: Deploy with docker-compose over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AIOLOS_PROD_EC2_HOST }}
          username: ${{ secrets.AIOLOS_PROD_EC2_USER }}
          key: ${{ secrets.RESONECT_AWS_PROD_SSH_KEY }}
          envs: AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_REGION
          script: |
            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            export AWS_REGION=$AWS_REGION
            
            # Login to ECR
            echo "Logging in to Amazon ECR..."
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.RESONECT_AWS_PROD_ID }}.dkr.ecr.eu-central-1.amazonaws.com
            
            cd ~/aiolos
            
            # Get CPU architecture
            ARCH=$(uname -m)
            echo "Running on architecture: $ARCH"
            
            # Pull and start services
            echo "Pulling latest container images..."
            docker compose -f docker-compose.prod.yml pull
            
            echo "Starting services..."
            docker compose -f docker-compose.prod.yml up -d --remove-orphans
            
            # Wait for the backend container to become healthy
            echo "Waiting for backend container to be healthy..."
            # This loop will wait for the container to be in a 'healthy' state.
            # It will timeout after 2 minutes (12 * 10 seconds).
            for i in $(seq 1 12); do
              STATUS=$(docker inspect --format '{{.State.Health.Status}}' aiolos-backend)
              if [ "$STATUS" = "healthy" ]; then
                echo "Backend is healthy!"
                break
              fi
              echo "Backend status is '$STATUS'. Waiting..."
              sleep 10
            done

            # Final check on container status
            echo "Final container status:"
            docker compose -f docker-compose.prod.yml ps
            
            # Check backend logs to diagnose any issues
            echo "Backend container logs:"
            docker compose -f docker-compose.prod.yml logs backend --tail 50

