name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and push Docker image for NestJS
        run: |
          docker build -t aiolos-backend:latest -f backend/aiolos-backend/Dockerfile ./backend
          docker push ghcr.io/${{ github.repository_owner }}/aiolos-backend:latest

      - name: Build and push Docker image for Next.js
        run: |
          docker build -t aiolos-frontend:latest -f frontend/aiolos-frontend/Dockerfile ./frontend
          docker push ghcr.io/${{ github.repository_owner }}/aiolos-frontend:latest

  deploy_to_vm:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            docker pull ghcr.io/${{ github.repository_owner }}/aiolos-backend:latest
            docker pull ghcr.io/${{ github.repository_owner }}/aiolos-frontend:latest
            cd /home/kuba/aiolos
            docker-compose down
            docker-compose up -d
          EOF
