name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUB_ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          docker build -t ghcr.io/${{ github.repository }}/aiolos-backend:latest -f backend/Dockerfile ./backend
          docker build -t ghcr.io/${{ github.repository }}/aiolos-frontend:latest -f frontend/Dockerfile ./frontend
          docker push ghcr.io/${{ github.repository }}/aiolos-backend:latest
          docker push ghcr.io/${{ github.repository }}/aiolos-frontend:latest

  deploy_to_vm:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            docker pull ghcr.io/${{ github.repository }}/aiolos-backend:latest
            docker pull ghcr.io/${{ github.repository }}/aiolos-frontend:latest
            docker-compose -f /home/kuba/aiolos/compose.yaml down
            docker-compose -f /home/kuba/aiolos/compose.yaml up -d
          EOF
