name: Test Aiolos Backend

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    name: Test Backend API
    runs-on: ubuntu-latest
    container: node:20-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: apk add --no-cache python3 make g++

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        working-directory: ./apps/adonis-api
        run: pnpm install --no-frozen-lockfile

      - name: Run database migrations
        working-directory: ./apps/adonis-api
        run: node ace migration:run --force
        env:
          NODE_ENV: test
          APP_KEY: test-key-for-ci-testing-only-not-secure
          DB_CONNECTION: sqlite
          PORT: 3333
          HOST: localhost
          LOG_LEVEL: error

      - name: Run tests
        working-directory: ./apps/adonis-api
        run: pnpm test
        env:
          NODE_ENV: test
          APP_KEY: test-key-for-ci-testing-only-not-secure
          DB_CONNECTION: sqlite
          PORT: 3333
          HOST: localhost
          LOG_LEVEL: error